# Generated by Django 2.0.5 on 2018-12-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiezaEjecucion',
            fields=[
                ('nPieza', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
