# Generated by Django 2.1.4 on 2018-12-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    

    operations = [
        migrations.CreateModel(
            name='Ejecucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
