# Generated by Django 2.1.4 on 2018-12-26 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pieza', '0002_ejecucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiezaEje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nPieza', models.IntegerField()),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pieza.Ejecucion')),
            ],
        ),
    ]
