# Generated by Django 2.1.4 on 2019-01-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pieza', '0003_piezaeje'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoGeneral',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Pieza.Ejecucion')),
                ('tiempoMax', models.FloatField()),
                ('tiempoMin', models.FloatField()),
                ('tiempoMedio', models.FloatField()),
                ('SA', models.FloatField()),
                ('SR', models.FloatField()),
                ('NA', models.FloatField()),
                ('NR', models.FloatField()),
            ],
        ),
    ]
