# Generated by Django 2.1.4 on 2019-01-05 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pieza', '0004_resultadogeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiezaResultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nPieza', models.IntegerField()),
                ('tiempoEsperado', models.FloatField()),
                ('tiempoTotal', models.FloatField()),
                ('diferenciaAde', models.FloatField()),
                ('diferenciaRetra', models.FloatField()),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pieza.Ejecucion')),
            ],
        ),
    ]
