# Generated by Django 2.1.4 on 2019-01-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pieza', '0006_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='brightness',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fase',
            name='color',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fase',
            name='nPiezaEje',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
