# Generated by Django 2.1.4 on 2019-01-17 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pieza', '0007_auto_20190112_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosInput',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Pieza.Ejecucion')),
                ('nPiezaEje', models.IntegerField()),
                ('nFase', models.IntegerField()),
                ('tiempoRequerido', models.FloatField()),
                ('maquinaNecesaria', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('tiempoEs', models.FloatField()),
                ('index', models.IntegerField()),
            ],
        ),
    ]
