# Generated by Django 2.1.4 on 2019-01-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pieza', '0008_datosinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosinput',
            name='ejecucion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Pieza.Ejecucion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datosinput',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
