# Generated by Django 2.1.4 on 2019-01-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pieza', '0011_piezaresultado_indiceresultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezaresultado',
            name='algoritmo',
            field=models.CharField(default='spt', max_length=50),
            preserve_default=False,
        ),
    ]
