# Generated by Django 2.1.4 on 2019-01-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pieza', '0014_auto_20190127_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoFinal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tiempoMax', models.FloatField()),
                ('tiempoMin', models.FloatField()),
                ('tiempoMedio', models.FloatField()),
                ('SA', models.FloatField()),
                ('SR', models.FloatField()),
                ('NA', models.FloatField()),
                ('NR', models.FloatField()),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pieza.Ejecucion')),
            ],
        ),
        migrations.RemoveField(
            model_name='resultadogeneral',
            name='ejecucion',
        ),
        migrations.AlterField(
            model_name='resultadogeneral',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Pieza.Ejecucion'),
        ),
    ]
