# Generated by Django 2.1.4 on 2019-01-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pieza', '0016_auto_20190127_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='indiceResultado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
