# Generated by Django 2.1.4 on 2019-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pieza', '0017_fase_indiceresultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadofinal',
            name='algoritmo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadogeneral',
            name='algoritmo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
