# Generated by Django 2.1.4 on 2019-02-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pieza', '0019_fase_tiempomax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='tiempoMax',
            field=models.IntegerField(),
        ),
    ]
