# Generated by Django 2.0.5 on 2018-12-18 20:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('planificador', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fase',
            new_name='FaseEjecucion',
        ),
        migrations.RenameModel(
            old_name='Maquina',
            new_name='MaquinaEjecucion',
        ),
        migrations.RenameModel(
            old_name='Pieza',
            new_name='PiezaEjecucion',
        ),
    ]
